[package]
name = "kvqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
ciborium = "0.2.2"
serde = "1"
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite"] }
thiserror = "2"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
